### ISSUE TITLE
Mickey to Donald: Magical Adventure 3 FastROM

### ISSUE THREAD

**Issue by thomasgoldstein** [VitorVilela7/fastrom#3]
A FastROM hack of Mickey to Donald: Magical Adventure 3 (aka Magical Quest 3) has been released.
https://www.romhacking.net/hacks/6324/

Should it be added to this repo?

**Comment by VitorVilela7** [comment]
There is a lot of FastROM patches available with different distribution formats. The patches published on this repository contains the source code, patch and a few more technical information, so putting all of them here would cause some confusion. For that reason I think a wiki page containing all available FastROM patches will work better instead of putting them on this repository.
